name: CI

env:
  FORCE_COLOR: 2
  NODE: 24

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE }}
      - run: npm install
      - run: npm run lint
      - run: npm run typecheck
  test:
    name: ${{ matrix.os }} Node.js ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 24
          - 22
          - 20
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run test
      - run: npm run test:bundles
      - run: npm run test:regress
